(() => {
  "use strict";

  const SOURCE_DEFS = [
    {id:"phone-specs",label:"Phone Specs API",url:"https://raw.githubusercontent.com/rinehartwang1979/phone-specs-api/master/data/phones.json",kind:"json",minimum:100,quality:3},
    {id:"smartdevices",label:"Smartdevices",url:"https://raw.githubusercontent.com/sarangzambare/smartdevices_pricing/master/csv/data_clean.csv",kind:"csv",minimum:900,quality:2},
    {id:"stf",label:"STF Device DB",url:"https://raw.githubusercontent.com/DeviceFarmer/stf-device-db/master/data/devices-latest.json",kind:"json",minimum:350,quality:1}
  ];
  const accents = ["#8ba5ce","#94bf82","#d28f91","#d69a64","#a795ca","#74b3ad","#d5b66f","#91a09a"];
  const knownBrands = ["Sony Ericsson","BlackBerry","Fairphone","Blackview","Microsoft","Motorola","Panasonic","OnePlus","Samsung","Xiaomi","Huawei","Google","Apple","Nothing","Nokia","Realme","Tecno","Infinix","Alcatel","Lenovo","Honor","ASUS","Asus","Oppo","Vivo","Sony","HTC","Acer","Amazon","Archos","Coolpad","Gionee","Meizu","Sharp","Philips","Micromax","Ulefone","Wiko","Lava","Dell","TCL","ZTE","BLU","CAT","LG"].sort((a,b)=>b.length-a.length);
  const fields = ["brand","model","price","os","screen","hz","chip","ram","storage","camera","zoom","battery","charge","weight","water","screenType","resolution","front","video","wireless","dimensions","material","network5g","nfc","launchDate","sim"];

  const fallbackSeed = [
    {id:"iphone-16-pro",brand:"Apple",model:"iPhone 16 Pro",price:109990,os:"iOS",screen:6.3,hz:120,chip:"Apple A18 Pro",ram:8,storage:256,camera:48,zoom:5,battery:3582,charge:27,weight:199,score:93,features:["esim","wireless","telephoto"],water:"IP68",network5g:true,nfc:true,launchDate:"2024",quality:4},
    {id:"s25-ultra",brand:"Samsung",model:"Galaxy S25 Ultra",price:119990,os:"Android",screen:6.9,hz:120,chip:"Snapdragon 8 Elite",ram:12,storage:256,camera:200,zoom:5,battery:5000,charge:45,weight:218,score:96,features:["esim","wireless","telephoto","fast"],water:"IP68",network5g:true,nfc:true,launchDate:"2025",quality:4},
    {id:"pixel-10-pro",brand:"Google",model:"Pixel 10 Pro",price:104990,os:"Android",screen:6.3,hz:120,chip:"Google Tensor G5",ram:16,storage:128,camera:50,zoom:5,battery:4870,charge:30,weight:207,score:92,features:["esim","wireless","telephoto"],water:"IP68",network5g:true,nfc:true,launchDate:"2025",quality:4},
    {id:"pixel-9a",brand:"Google",model:"Pixel 9a",price:49990,os:"Android",screen:6.3,hz:120,chip:"Google Tensor G4",ram:8,storage:128,camera:48,zoom:2,battery:5100,charge:23,weight:186,score:84,features:["esim","wireless"],water:"IP68",network5g:true,nfc:true,launchDate:"2025",quality:4},
    {id:"oneplus-13",brand:"OnePlus",model:"OnePlus 13",price:74990,os:"Android",screen:6.82,hz:120,chip:"Snapdragon 8 Elite",ram:12,storage:256,camera:50,zoom:3,battery:6000,charge:100,weight:210,score:95,features:["esim","wireless","telephoto","fast"],water:"IP69",network5g:true,nfc:true,launchDate:"2024",quality:4},
    {id:"xiaomi-15",brand:"Xiaomi",model:"Xiaomi 15",price:69990,os:"Android",screen:6.36,hz:120,chip:"Snapdragon 8 Elite",ram:12,storage:256,camera:50,zoom:2.6,battery:5240,charge:90,weight:191,score:93,features:["esim","wireless","telephoto","fast"],water:"IP68",network5g:true,nfc:true,launchDate:"2024",quality:4},
    {id:"nothing-3",brand:"Nothing",model:"Phone (3)",price:69990,os:"Android",screen:6.67,hz:120,chip:"Snapdragon 8s Gen 4",ram:12,storage:256,camera:50,zoom:3,battery:5150,charge:65,weight:218,score:87,features:["esim","wireless","telephoto","fast"],water:"IP68",network5g:true,nfc:true,launchDate:"2025",quality:4},
    {id:"zenfone-12",brand:"ASUS",model:"Zenfone 12 Ultra",price:89990,os:"Android",screen:6.78,hz:144,chip:"Snapdragon 8 Elite",ram:16,storage:512,camera:50,zoom:3,battery:5500,charge:65,weight:220,score:90,features:["esim","wireless","telephoto","fast"],water:"IP68",network5g:true,nfc:true,launchDate:"2025",quality:4}
  ];

  const I18N = {
    ru:{catalog:"Каталог",compare:"Сравнение",eyebrow:"✦ умный подбор смартфона",hero1:"Сравнивай глубже.",hero2:"Выбирай точнее.",heroCopy:"Ищи не только по названию — пиши требования обычными словами.",placeholder:"Например: компактный Android с eSIM…",cameraQuery:"камерофон 120 Гц",compactQuery:"компактный с eSIM",batteryQuery:"автономный Android",dbLoading:(r,t,n)=>`Загружаем базы: ${r}/${t} · уже ${n} моделей`,dbReady:(r,t,n)=>`${r}/${t} баз подключено · ${n} уникальных моделей`,dbFallback:"Внешние базы недоступны — работает резервный каталог",loading:"загрузка",failed:"ошибка",filters:"☷ Фильтры",reset:"Сбросить",brand:"Бренд",priceTo:"Цена до",features:"Возможности",best:"Сначала лучшие",cheap:"Сначала дешевле",expensive:"Сначала дороже",batterySort:"Больше батарея",newest:"Сначала новые",face:"Лицом к лицу",deep:"Глубокое сравнение",compareCopy:"Лучшее значение в каждой строке подсвечено.",footer:"PhoNNeR объединяет Phone Specs API, Smartdevices, STF Device DB и локальную базу. Полнота полей зависит от источника; цены ориентировочные.",phones:n=>`${n} ${n%10===1&&n%100!==11?"смартфон":n%10>=2&&n%10<=4&&(n%100<10||n%100>=20)?"смартфона":"смартфонов"}`,from:"от",unknown:"нет данных",added:"✓ Добавлен",add:"⇄ Сравнить",empty:"Ничего не нашлось",emptyCopy:"Убери один из фильтров или сократи запрос.",more:"Показать ещё",oneMore:"+ ещё один",choose:n=>`Выбери ещё ${n} смартфон для сравнения.`,score:"Сводная оценка",price:"Цена",screen:"Экран",screenType:"Тип экрана",resolution:"Разрешение",chip:"Процессор",memory:"Память",camera:"Основная камера",front:"Фронтальная камера",video:"Видео",battery:"Батарея",charge:"Зарядка",wireless:"Беспроводная зарядка",weight:"Вес",water:"Защита",network:"Сеть",nfc:"NFC",dimensions:"Размеры",material:"Материал",launch:"Дата выхода",sources:"Источники",yes:"Да",no:"Нет",auto:"Авто",themeSystem:"Тема: системная",themeLight:"Тема: светлая",themeDark:"Тема: тёмная",esim:"eSIM",telephoto:"Телеобъектив",fast:"Быстрая зарядка"},
    en:{catalog:"Catalog",compare:"Compare",eyebrow:"✦ smart phone finder",hero1:"Compare deeper.",hero2:"Choose smarter.",heroCopy:"Search beyond model names — describe what you need in plain language.",placeholder:"Example: compact Android with eSIM…",cameraQuery:"camera phone 120 Hz",compactQuery:"compact with eSIM",batteryQuery:"long battery Android",dbLoading:(r,t,n)=>`Loading databases: ${r}/${t} · ${n} models so far`,dbReady:(r,t,n)=>`${r}/${t} databases connected · ${n} unique models`,dbFallback:"External databases unavailable — using the fallback catalog",loading:"loading",failed:"failed",filters:"☷ Filters",reset:"Reset",brand:"Brand",priceTo:"Price up to",features:"Features",best:"Best first",cheap:"Lowest price",expensive:"Highest price",batterySort:"Largest battery",newest:"Newest first",face:"Head to head",deep:"Deep comparison",compareCopy:"The better value in each row is highlighted.",footer:"PhoNNeR unifies Phone Specs API, Smartdevices, STF Device DB and a local catalog. Field coverage varies by source; prices are estimates.",phones:n=>`${n} phones`,from:"from",unknown:"no data",added:"✓ Added",add:"⇄ Compare",empty:"No matches",emptyCopy:"Remove a filter or shorten your query.",more:"Show more",oneMore:"+ one more",choose:n=>`Choose ${n} more phone to compare.`,score:"Overall score",price:"Price",screen:"Display",screenType:"Display type",resolution:"Resolution",chip:"Chipset",memory:"Memory",camera:"Main camera",front:"Front camera",video:"Video",battery:"Battery",charge:"Charging",wireless:"Wireless charging",weight:"Weight",water:"Protection",network:"Network",nfc:"NFC",dimensions:"Dimensions",material:"Material",launch:"Launch date",sources:"Sources",yes:"Yes",no:"No",auto:"Auto",themeSystem:"Theme: system",themeLight:"Theme: light",themeDark:"Theme: dark",esim:"eSIM",telephoto:"Telephoto",fast:"Fast charging"},
    uk:{catalog:"Каталог",compare:"Порівняння",eyebrow:"✦ розумний підбір смартфона",hero1:"Порівнюй глибше.",hero2:"Обирай точніше.",heroCopy:"Шукай не лише за назвою — опиши вимоги звичайними словами.",placeholder:"Наприклад: компактний Android з eSIM…",cameraQuery:"камерофон 120 Гц",compactQuery:"компактний з eSIM",batteryQuery:"автономний Android",dbLoading:(r,t,n)=>`Завантажуємо бази: ${r}/${t} · вже ${n} моделей`,dbReady:(r,t,n)=>`${r}/${t} баз підключено · ${n} унікальних моделей`,dbFallback:"Зовнішні бази недоступні — працює резервний каталог",loading:"завантаження",failed:"помилка",filters:"☷ Фільтри",reset:"Скинути",brand:"Бренд",priceTo:"Ціна до",features:"Можливості",best:"Спочатку найкращі",cheap:"Спочатку дешевші",expensive:"Спочатку дорожчі",batterySort:"Більша батарея",newest:"Спочатку нові",face:"Віч-на-віч",deep:"Глибоке порівняння",compareCopy:"Найкраще значення в кожному рядку підсвічено.",footer:"PhoNNeR об’єднує Phone Specs API, Smartdevices, STF Device DB і локальний каталог. Повнота полів залежить від джерела; ціни орієнтовні.",phones:n=>`${n} смартфонів`,from:"від",unknown:"немає даних",added:"✓ Додано",add:"⇄ Порівняти",empty:"Нічого не знайдено",emptyCopy:"Прибери фільтр або скороти запит.",more:"Показати ще",oneMore:"+ ще один",choose:n=>`Обери ще ${n} смартфон для порівняння.`,score:"Загальна оцінка",price:"Ціна",screen:"Екран",screenType:"Тип екрана",resolution:"Роздільність",chip:"Процесор",memory:"Пам’ять",camera:"Основна камера",front:"Фронтальна камера",video:"Відео",battery:"Батарея",charge:"Заряджання",wireless:"Бездротове заряджання",weight:"Вага",water:"Захист",network:"Мережа",nfc:"NFC",dimensions:"Розміри",material:"Матеріал",launch:"Дата виходу",sources:"Джерела",yes:"Так",no:"Ні",auto:"Авто",themeSystem:"Тема: системна",themeLight:"Тема: світла",themeDark:"Тема: темна",esim:"eSIM",telephoto:"Телеоб’єктив",fast:"Швидке заряджання"},
    es:{catalog:"Catálogo",compare:"Comparar",eyebrow:"✦ buscador inteligente",hero1:"Compara mejor.",hero2:"Elige con precisión.",heroCopy:"Busca más allá del nombre: describe lo que necesitas.",placeholder:"Ejemplo: Android compacto con eSIM…",cameraQuery:"móvil cámara 120 Hz",compactQuery:"compacto con eSIM",batteryQuery:"Android gran batería",dbLoading:(r,t,n)=>`Cargando bases: ${r}/${t} · ${n} modelos`,dbReady:(r,t,n)=>`${r}/${t} bases conectadas · ${n} modelos únicos`,dbFallback:"Bases externas no disponibles — usando el catálogo de reserva",loading:"cargando",failed:"error",filters:"☷ Filtros",reset:"Restablecer",brand:"Marca",priceTo:"Precio hasta",features:"Funciones",best:"Mejores primero",cheap:"Más baratos",expensive:"Más caros",batterySort:"Mayor batería",newest:"Más nuevos",face:"Cara a cara",deep:"Comparación profunda",compareCopy:"El mejor valor de cada fila está resaltado.",footer:"PhoNNeR unifica Phone Specs API, Smartdevices, STF Device DB y un catálogo local. La cobertura varía según la fuente; los precios son estimaciones.",phones:n=>`${n} teléfonos`,from:"desde",unknown:"sin datos",added:"✓ Añadido",add:"⇄ Comparar",empty:"Sin resultados",emptyCopy:"Quita un filtro o acorta la búsqueda.",more:"Mostrar más",oneMore:"+ uno más",choose:n=>`Elige ${n} teléfono más para comparar.`,score:"Puntuación",price:"Precio",screen:"Pantalla",screenType:"Tipo de pantalla",resolution:"Resolución",chip:"Procesador",memory:"Memoria",camera:"Cámara principal",front:"Cámara frontal",video:"Vídeo",battery:"Batería",charge:"Carga",wireless:"Carga inalámbrica",weight:"Peso",water:"Protección",network:"Red",nfc:"NFC",dimensions:"Dimensiones",material:"Material",launch:"Lanzamiento",sources:"Fuentes",yes:"Sí",no:"No",auto:"Auto",themeSystem:"Tema: sistema",themeLight:"Tema: claro",themeDark:"Tema: oscuro",esim:"eSIM",telephoto:"Teleobjetivo",fast:"Carga rápida"}
  };

  const $ = selector => document.querySelector(selector);
  const num = value => Number(String(value ?? "").replace(",", ".").match(/\d+(?:\.\d+)?/)?.[0] || 0);
  const clamp = (value,min,max) => Math.max(min,Math.min(max,value));
  const slug = value => String(value||"").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9а-яё]+/g,"-").replace(/^-|-$/g,"");
  const canonicalBrand = value => {const raw=String(value||"Unknown").trim();const hit=knownBrands.find(brand=>brand.toLowerCase()===raw.toLowerCase());return hit?hit.replace("Asus","ASUS").replace("Zte","ZTE").replace("Htc","HTC").replace("Lg","LG"):raw.replace(/\b\w/g,char=>char.toUpperCase())};
  const inferBrand = name => canonicalBrand(knownBrands.find(brand=>String(name).toLowerCase().startsWith(brand.toLowerCase()+" "))||String(name).trim().split(/\s+/)[0]||"Unknown");
  const cleanModel = (brand,name) => String(name||"Unknown").trim().replace(new RegExp(`^${String(brand).replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\s+`,"i"),"").trim()||String(name||"Unknown").trim();
  const keyOf = phone => slug(`${canonicalBrand(phone.brand)} ${cleanModel(phone.brand,phone.model)}`);
  const brandAccent = brand => accents[[...String(brand)].reduce((sum,char)=>sum+char.charCodeAt(0),0)%accents.length];
  const isMissing = value => value===undefined||value===null||value===""||value==="—"||(typeof value==="number"&&!Number.isFinite(value))||value===0;
  const parseBool = value => {if(typeof value==="boolean")return value;if(value===1||value==="1")return true;if(value===0||value==="0")return false;const text=String(value??"").trim().toLowerCase();if(!text)return null;if(/^(yes|true|supported|available)/.test(text))return true;if(/^(no|false|unsupported)/.test(text))return false;return null};
  const yearOf = value => num(String(value||"").match(/(?:19|20)\d{2}/)?.[0]);
  function computeScore(phone){const year=yearOf(phone.launchDate);return clamp(Math.round(38+Math.min(phone.hz||60,144)/9+Math.min(phone.ram||0,16)*.65+Math.min(phone.storage||0,512)/90+Math.min(phone.camera||0,200)/22+Math.min(phone.battery||0,6000)/900+(phone.network5g?3:0)+(phone.nfc?2:0)+(year?clamp((year-2014)*1.15,0,13):0)),35,98)}
  function complete(phone){const result={price:0,os:"—",screen:0,hz:0,chip:"—",ram:0,storage:0,camera:0,zoom:0,battery:0,charge:0,weight:0,score:0,features:[],water:"—",screenType:"—",resolution:"—",front:0,video:"—",wireless:"—",dimensions:"—",material:"—",network5g:null,nfc:null,launchDate:"—",sim:"—",quality:0,sources:[],...phone};result.brand=canonicalBrand(result.brand);result.model=cleanModel(result.brand,result.model);result.accent=result.accent||brandAccent(result.brand);result.features=[...new Set(result.features||[])];result.score=result.score||computeScore(result);result.source=result.sources.join(" + ");return result}
  const fallback = fallbackSeed.map((phone,index)=>complete({...phone,accent:accents[index%accents.length],sources:["PhoNNeR"]}));

  function normalizePhoneSpecs(raw,index){
    const brand=canonicalBrand(raw.brand),model=cleanModel(brand,raw.model_name||raw.model),screen=num(raw.screen_size),hz=num(raw.refresh_rate),ram=num(raw.ram),storage=num(raw.storage),camera=num(raw.rear_camera_main),battery=num(raw.battery_capacity),charge=num(raw.charging_wired),weight=num(raw.weight);
    const cameraText=String(raw.rear_camera_specs||raw.camera||"").toLowerCase(),sim=String(raw.sim_type||""),wireless=raw.charging_wireless;
    const features=[];if(/esim/i.test(sim))features.push("esim");if(parseBool(wireless)===true||num(wireless)>0)features.push("wireless");if(/tele|periscope|长焦|潜望/i.test(cameraText))features.push("telephoto");if(parseBool(raw.fast_charging)===true||charge>=45)features.push("fast");
    return complete({id:`ps-${slug(raw.id||`${brand}-${model}-${index}`)}`,brand,model,price:0,os:/ios/i.test(raw.os||"")?"iOS":raw.os||"Android",screen,hz,chip:raw.chipset||"—",ram,storage,camera,zoom:num(raw.optical_zoom),battery,charge,weight,features,water:raw.water_resistance||"—",screenType:raw.screen_type||"—",resolution:raw.resolution||"—",front:num(raw.front_camera),video:raw.video||raw.video_recording||"—",wireless:wireless||"—",dimensions:raw.dimensions||"—",material:raw.material||"—",network5g:parseBool(raw.network_5g)??/5g/i.test(String(raw.network||"")),nfc:parseBool(raw.nfc),launchDate:raw.launch_date||"—",sim:sim||"—",quality:3,sources:["Phone Specs API"]});
  }
  function parseCSV(text){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(char===","&&!quoted){row.push(field);field=""}else if((char==="\n"||char==="\r")&&!quoted){if(char==="\r"&&text[i+1]==="\n")i++;row.push(field);if(row.some(cell=>cell!==""))rows.push(row);row=[];field=""}else field+=char}if(field||row.length){row.push(field);rows.push(row)}return rows}
  function normalizeSmartdevices(text){const rows=parseCSV(text),header=rows.shift().map(value=>value.trim());return rows.map((row,index)=>{const raw=Object.fromEntries(header.map((key,i)=>[key,row[i]]));const name=String(raw.name||"").trim(),brand=inferBrand(name),model=cleanModel(brand,name),screen=num(raw.screen_size);if(!name||screen>7.25||/\b(watch|tab|tablet|gear)\b/i.test(name))return null;const storage=num(raw.internal),ram=num(raw.ram),camera=num(raw.camera),battery=num(raw.battery),weight=num(raw.weight),year=num(raw.year);return complete({id:`sd-${slug(name)}-${index}`,brand,model,price:0,os:/apple|iphone/i.test(name)?"iOS":/lumia|microsoft/i.test(name)?"Windows Phone":/blackberry/i.test(name)?"BlackBerry OS":"Android",screen,hz:0,chip:raw.cpu_ghz?`CPU ${num(raw.cpu_ghz)} GHz`:"—",ram,storage,camera,front:num(raw.front_cam),battery,weight,screenType:raw.display_type||"—",resolution:raw.ppi?`${num(raw.ppi)} ppi`:"—",network5g:false,nfc:null,launchDate:year?String(year):"—",sim:parseBool(raw.LTE)?"LTE":"—",quality:2,sources:["Smartdevices"]})}).filter(Boolean)}
  function normalizeStf(data){return Object.entries(data||{}).map(([code,raw],index)=>{const name=raw?.name?.id||raw?.name?.long||code,brand=canonicalBrand(raw?.maker?.name||inferBrand(name)),model=cleanModel(brand,name),screen=num(raw?.display?.s);if(!name||screen>7.25||/\b(watch|tab|tablet|ipad|gear)\b/i.test(name))return null;const ram=Math.round((num(raw?.memory?.ram)/1024)*100)/100,storage=Math.round((num(raw?.memory?.rom)/1024)*100)/100,resolution=raw?.display?.w&&raw?.display?.h?`${raw.display.w} × ${raw.display.h}`:"—",osType=String(raw?.os?.type||"Android");return complete({id:`stf-${slug(code||index)}`,brand,model,price:0,os:/ios/i.test(osType)?"iOS":/win/i.test(osType)?"Windows Phone":/android/i.test(osType)?"Android":osType,screen,hz:0,chip:raw?.cpu?.name||"—",ram,storage,camera:0,battery:0,weight:0,resolution,network5g:null,nfc:null,launchDate:raw?.date||"—",quality:1,sources:["STF Device DB"]})}).filter(Boolean)}

  const phoneMap = new Map(fallback.map(phone=>[keyOf(phone),phone]));
  let phones=[...phoneMap.values()],selected=["s25-ultra","oneplus-13"],brandSet=new Set(),featureSet=new Set(),visibleLimit=48,lastSignature="",allSourcesDone=false;
  let languageChoice=localStorage.getItem("phonner-language")||"auto",lang=languageChoice==="auto"?resolveLanguage():languageChoice,themeMode=localStorage.getItem("phonner-theme")||"system";
  const sourceStates=new Map(SOURCE_DEFS.map(source=>[source.id,{...source,status:"loading",count:0}]));
  const search=$("#search"),price=$("#price"),sort=$("#sort");
  function resolveLanguage(){const code=(navigator.language||"en").toLowerCase();return code.startsWith("ru")?"ru":code.startsWith("uk")?"uk":code.startsWith("es")?"es":"en"}
  function t(key,...args){const value=(I18N[lang]||I18N.en)[key]??I18N.en[key]??key;return typeof value==="function"?value(...args):value}
  function money(value){return new Intl.NumberFormat(lang==="uk"?"uk-UA":lang==="ru"?"ru-RU":lang==="es"?"es-ES":"en-US").format(value)}
  function mergeRecord(existing,incoming){const merged={...existing};for(const field of fields){if(isMissing(incoming[field]))continue;if(isMissing(merged[field])||incoming.quality>existing.quality)merged[field]=incoming[field]}merged.id=existing.id;merged.quality=Math.max(existing.quality||0,incoming.quality||0);merged.features=[...new Set([...(existing.features||[]),...(incoming.features||[])])];merged.sources=[...new Set([...(existing.sources||[]),...(incoming.sources||[])])];merged.accent=existing.accent||incoming.accent;merged.score=Math.max(existing.score||0,incoming.score||0,computeScore(merged));merged.source=merged.sources.join(" + ");return complete(merged)}
  function ingest(records){for(const phone of records){if(!phone?.brand||!phone?.model)continue;const key=keyOf(phone),existing=phoneMap.get(key);phoneMap.set(key,existing?mergeRecord(existing,phone):phone)}phones=[...phoneMap.values()].sort((a,b)=>yearOf(b.launchDate)-yearOf(a.launchDate)||b.score-a.score);buildSearchIndex();buildFilters();render();renderSources()}
  function buildSearchIndex(){phones.forEach(phone=>{phone._search=[phone.brand,phone.model,phone.os,phone.chip,phone.screenType,phone.resolution,phone.water,phone.sim,...phone.features,phone.hz+" hz гц",phone.ram+" gb гб",phone.storage+" gb гб",phone.camera+" mp мп",phone.battery+" mah мач",phone.sources.join(" ")].join(" ").toLowerCase().replaceAll("ё","е")})}
  async function fetchWithTimeout(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{const response=await fetch(url,{cache:"force-cache",signal:controller.signal});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response}finally{clearTimeout(timer)}}
  async function loadSource(def){const state=sourceStates.get(def.id);try{const response=await fetchWithTimeout(def.url);const payload=def.kind==="csv"?await response.text():await response.json();const records=def.id==="phone-specs"?(Array.isArray(payload)?payload.map(normalizePhoneSpecs):[]):def.id==="smartdevices"?normalizeSmartdevices(payload):normalizeStf(payload);if(records.length<def.minimum)throw new Error(`Only ${records.length} records`);state.status="ready";state.count=records.length;ingest(records)}catch(error){state.status="failed";state.error=String(error?.message||error);console.warn(`PhoNNeR source ${def.label} failed`,error);renderSources()}}
  async function loadDatabases(){renderSources();await Promise.allSettled(SOURCE_DEFS.map(loadSource));allSourcesDone=true;renderSources()}
  function renderSources(){const states=[...sourceStates.values()],ready=states.filter(state=>state.status==="ready").length,failed=states.filter(state=>state.status==="failed").length;$("#db-sources").innerHTML=states.map(state=>`<span class="db-source ${state.status}" title="${escapeHtml(state.url)}"><i></i><b>${escapeHtml(state.label)}</b> ${state.status==="ready"?money(state.count):t(state.status)}</span>`).join("");const dot=$("#db-dot");dot.className=`db-dot ${allSourcesDone&&ready?"ready":ready?"partial":""}`;$("#db-status").textContent=allSourcesDone?(ready?t("dbReady",ready,states.length,phones.length):t("dbFallback")):t("dbLoading",ready,states.length,phones.length);if(allSourcesDone&&failed&&ready)dot.classList.add("partial")}

  function matchPhone(phone,query){const q=query.toLowerCase().replaceAll("ё","е").trim();if(!q)return true;return q.split(/\s+/).every(token=>{if(["флагман","топ","flagship","premium"].includes(token))return phone.score>=90;if(["компактный","маленький","compact","compacto"].includes(token))return phone.screen>0&&phone.screen<=6.4;if(["автономный","батарея","battery","batería"].includes(token))return phone.battery>=5000;if(["камера","камерофон","camera","cámara"].includes(token))return phone.camera>=48;if(["андроид","android"].includes(token))return /android/i.test(phone.os);if(["айфон","iphone","ios"].includes(token))return phone.os==="iOS";const amount=Number(token.replace(/\D/g,""));if(amount>=20000)return phone.price>0&&phone.price<=amount;return phone._search.includes(token)})}
  function filteredPhones(){let list=phones.filter(phone=>matchPhone(phone,search.value)&&((phone.price>0&&phone.price<=+price.value)||(phone.price===0&&+price.value===130000))&&(!brandSet.size||brandSet.has(phone.brand))&&[...featureSet].every(feature=>phone.features.includes(feature)));list.sort((a,b)=>sort.value==="asc"?(a.price||Infinity)-(b.price||Infinity):sort.value==="desc"?(b.price||-1)-(a.price||-1):sort.value==="battery"?b.battery-a.battery:sort.value==="newest"?yearOf(b.launchDate)-yearOf(a.launchDate):b.score-a.score);return list}
  function phoneSummary(phone){return [phone.chip,phone.screenType,phone.battery?`${phone.battery} mAh`:""].filter(value=>value&&value!=="—").join(" · ")||t("unknown")}
  function render(){const signature=[search.value,price.value,sort.value,[...brandSet].join(),[...featureSet].join(),lang,phones.length].join("|");if(signature!==lastSignature){visibleLimit=48;lastSignature=signature}const list=filteredPhones(),shown=list.slice(0,visibleLimit);$("#result-title").textContent=t("phones",list.length);$("#price-label").textContent=money(+price.value)+" ₽";$("#clear").style.display=search.value?"block":"none";$("#grid").innerHTML=shown.length?shown.map((phone,index)=>`<article class="card" style="--phone:${phone.accent};animation-delay:${Math.min(index,5)*35}ms"><div class="card-top"><span class="orb"><i>${escapeHtml(phone.brand[0]||"?")}</i></span><span class="score"><b>${phone.score}</b><small>/100</small></span></div><div class="title"><small>${escapeHtml(phone.brand)} · ${escapeHtml(phone.os)}</small><h3>${escapeHtml(phone.model)}</h3><p>${escapeHtml(phoneSummary(phone))}</p></div><div class="specs"><span>◫ ${phone.screen||"—"}″ · ${phone.hz||"—"} Hz</span><span>◈ ${phone.ram||"—"}/${phone.storage||"—"} GB</span><span>◎ ${phone.camera||"—"} MP</span><span>ϟ ${phone.battery||"—"} mAh</span></div><div class="bottom"><div class="price"><small>${phone.price?t("from"):t("price")}</small><b>${phone.price?money(phone.price)+" ₽":t("unknown")}</b><span class="source-tag" title="${escapeHtml(phone.source)}">${escapeHtml(phone.source)}</span></div><button class="add ${selected.includes(phone.id)?"on":""}" data-id="${escapeHtml(phone.id)}">${selected.includes(phone.id)?t("added"):t("add")}</button></div></article>`).join(""):`<div class="empty"><b>${t("empty")}</b><p>${t("emptyCopy")}</p></div>`;const more=$("#load-more");more.style.display=list.length>visibleLimit?"block":"none";more.textContent=`${t("more")} · ${Math.max(0,list.length-visibleLimit)}`;document.querySelectorAll(".add").forEach(button=>button.onclick=()=>toggle(button.dataset.id));dock()}
  function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]))}
  function toggle(id){selected=selected.includes(id)?selected.filter(item=>item!==id):selected.length<2?[...selected,id]:[selected[1],id];render()}
  function dock(){const pair=selected.map(id=>phones.find(phone=>phone.id===id)).filter(Boolean);$("#nav-count").textContent=selected.length;$("#dock-items").innerHTML=pair.map(phone=>`<span>${escapeHtml(phone.model)} <button data-x="${escapeHtml(phone.id)}" aria-label="Remove">×</button></span>`).join("")+(selected.length<2?`<span>${t("oneMore")}</span>`:"");document.querySelectorAll("[data-x]").forEach(button=>button.onclick=()=>toggle(button.dataset.x));$("#dock-action").className=selected.length===2?"":"off";$("#dock-action").textContent=t("compare")+" →";compare(pair)}
  function value(phone,key){return phone[key]===0||phone[key]===false?phone[key]:phone[key]||"—"}
  function compare(pair){
    const out=$("#comparison");
    if(pair.length<2){out.innerHTML=`<div class="nothing">${t("choose",2-pair.length)}</div>`;return}
    const unknownBoolean=value=>value==="—"||value===null;
    const rows=[
      ["score","score","max",value=>`${value} / 100`],
      ["price","price","min",value=>value?`${money(value)} ₽`:t("unknown")],
      ["screen","screen","none",(value,index)=>`${value||"—"}″ · ${pair[index].hz||"—"} Hz`],
      ["screenType","screenType","none",value=>value],["resolution","resolution","none",value=>value],["chip","chip","none",value=>value],
      ["memory","ram","max",(value,index)=>`${value||"—"} / ${pair[index].storage||"—"} GB`],
      ["camera","camera","max",value=>value?`${value} MP`:"—"],["front","front","max",value=>value?`${value} MP`:"—"],["video","video","none",value=>value],
      ["battery","battery","max",value=>value?`${money(value)} mAh`:"—"],["charge","charge","max",value=>value?`${value} W`:"—"],["wireless","wireless","none",value=>value],["weight","weight","min",value=>value?`${value} g`:"—"],["water","water","none",value=>value],
      ["network","network5g","boolean",value=>unknownBoolean(value)?"—":value?"5G":"4G"],["nfc","nfc","boolean",value=>unknownBoolean(value)?"—":value?t("yes"):t("no")],
      ["dimensions","dimensions","none",value=>value],["material","material","none",value=>value],["launch","launchDate","none",value=>value],["sources","sources","none",value=>Array.isArray(value)?value.join(" · "):value]
    ];
    out.innerHTML=`<div class="table"><div class="row"><div></div><div>${escapeHtml(pair[0].model)}</div><div>${escapeHtml(pair[1].model)}</div></div>${rows.map(row=>{const values=pair.map(phone=>value(phone,row[1])),numeric=values.every(item=>typeof item==="number"&&item>0),best=numeric&&row[2]==="max"?Math.max(...values):numeric&&row[2]==="min"?Math.min(...values):null;return `<div class="row"><div>${t(row[0])}</div>${values.map((item,index)=>`<div class="${best!==null&&item===best&&values[0]!==values[1]?"winner":""}">${best!==null&&item===best&&values[0]!==values[1]?"✓ ":""}${escapeHtml(row[3](item,index))}</div>`).join("")}</div>`}).join("")}</div>`;
  }
  function buildFilters(){const counts=new Map();phones.forEach(phone=>counts.set(phone.brand,(counts.get(phone.brand)||0)+1));const brands=[...counts.keys()].sort((a,b)=>a.localeCompare(b));$("#brands").innerHTML=brands.map(brand=>`<label><input type="checkbox" value="${escapeHtml(brand)}" ${brandSet.has(brand)?"checked":""}><span>${escapeHtml(brand)}</span><small>${counts.get(brand)}</small></label>`).join("");document.querySelectorAll("#brands input").forEach(input=>input.onchange=()=>{input.checked?brandSet.add(input.value):brandSet.delete(input.value);render()});const featureKeys=["esim","wireless","telephoto","fast"];$("#features").innerHTML=featureKeys.map(key=>`<button class="pill ${featureSet.has(key)?"on":""}" data-f="${key}">${t(key)}</button>`).join("");document.querySelectorAll("[data-f]").forEach(button=>button.onclick=()=>{featureSet.has(button.dataset.f)?featureSet.delete(button.dataset.f):featureSet.add(button.dataset.f);button.classList.toggle("on");render()})}
  function applyLanguage(){document.documentElement.lang=lang;$("#nav-catalog").textContent=t("catalog");$("#nav-compare").textContent=t("compare");$("#eyebrow").textContent=t("eyebrow");$("#hero-title").innerHTML=`${t("hero1")}<br><span>${t("hero2")}</span>`;$("#hero-copy").textContent=t("heroCopy");search.placeholder=t("placeholder");const suggestions=document.querySelectorAll(".suggestions button");suggestions[0].textContent=t("cameraQuery");suggestions[1].textContent=t("compactQuery");suggestions[2].textContent=t("batteryQuery");$("#catalog-kicker").textContent=t("catalog");$("#filters-title").textContent=t("filters");$("#reset").textContent=t("reset");$("#brand-title").textContent=t("brand");$("#price-title").textContent=t("priceTo");$("#features-title").textContent=t("features");sort.options[0].text=t("best");sort.options[1].text=t("cheap");sort.options[2].text=t("expensive");sort.options[3].text=t("batterySort");sort.options[4].text=t("newest");$("#compare-kicker").textContent=t("face");$("#compare-title").textContent=t("deep");$("#compare-copy").textContent=t("compareCopy");$("#dock-title").textContent=`⇄ ${t("compare")}`;$("#footer-copy").textContent=t("footer");buildFilters();render();renderSources();updateThemeButton()}
  function effectiveDark(){return themeMode==="dark"||(themeMode==="system"&&matchMedia("(prefers-color-scheme: dark)").matches)}
  function applyTheme(){const dark=effectiveDark();document.documentElement.dataset.theme=dark?"dark":"light";document.documentElement.style.colorScheme=dark?"dark":"light";$("#theme-color").content=dark?"#090f0c":"#f4f6f3";updateThemeButton()}
  function updateThemeButton(){const button=$("#theme");button.textContent=themeMode==="system"?"◐":themeMode==="light"?"☀":"☾";button.title=t(themeMode==="system"?"themeSystem":themeMode==="light"?"themeLight":"themeDark");button.setAttribute("aria-label",button.title)}

  buildSearchIndex();[search,price,sort].forEach(input=>input.addEventListener("input",render));$("#clear").onclick=()=>{search.value="";render()};document.querySelectorAll(".suggestions button").forEach(button=>button.onclick=()=>{search.value=button.textContent;render();$("#catalog").scrollIntoView()});$("#reset").onclick=()=>{search.value="";price.value=130000;brandSet.clear();featureSet.clear();buildFilters();render()};$("#load-more").onclick=()=>{visibleLimit+=48;lastSignature=[search.value,price.value,sort.value,[...brandSet].join(),[...featureSet].join(),lang,phones.length].join("|");render()};
  $("#language").value=languageChoice;$("#language").onchange=event=>{languageChoice=event.target.value;localStorage.setItem("phonner-language",languageChoice);lang=languageChoice==="auto"?resolveLanguage():languageChoice;applyLanguage()};$("#theme").onclick=()=>{themeMode=themeMode==="system"?"light":themeMode==="light"?"dark":"system";localStorage.setItem("phonner-theme",themeMode);applyTheme()};matchMedia("(prefers-color-scheme: dark)").addEventListener("change",()=>{if(themeMode==="system")applyTheme()});document.addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key==="k"){event.preventDefault();search.focus()}});
  applyTheme();applyLanguage();loadDatabases();
})();
