(() => {
  "use strict";

  const DATABASE_URL = "https://raw.githubusercontent.com/rinehartwang1979/phone-specs-api/master/data/phones.json";
  const accents = ["#a9b6c8", "#89a8d8", "#bcc7aa", "#e1a0a0", "#efa56f", "#c5a8d9", "#9eb0a4", "#d7b58a"];
  const fallback = [
    {id:"iphone-16-pro",brand:"Apple",model:"iPhone 16 Pro",price:109990,os:"iOS",screen:6.3,hz:120,chip:"Apple A18 Pro",ram:8,storage:256,camera:48,zoom:5,battery:3582,charge:27,weight:199,score:93,features:["esim","wireless","telephoto"],water:"IP68",source:"PhoNNeR"},
    {id:"s25-ultra",brand:"Samsung",model:"Galaxy S25 Ultra",price:119990,os:"Android",screen:6.9,hz:120,chip:"Snapdragon 8 Elite",ram:12,storage:256,camera:200,zoom:5,battery:5000,charge:45,weight:218,score:96,features:["esim","wireless","telephoto"],water:"IP68",source:"PhoNNeR"},
    {id:"pixel-10-pro",brand:"Google",model:"Pixel 10 Pro",price:104990,os:"Android",screen:6.3,hz:120,chip:"Google Tensor G5",ram:16,storage:128,camera:50,zoom:5,battery:4870,charge:30,weight:207,score:92,features:["esim","wireless","telephoto"],water:"IP68",source:"PhoNNeR"},
    {id:"pixel-9a",brand:"Google",model:"Pixel 9a",price:49990,os:"Android",screen:6.3,hz:120,chip:"Google Tensor G4",ram:8,storage:128,camera:48,zoom:2,battery:5100,charge:23,weight:186,score:84,features:["esim","wireless"],water:"IP68",source:"PhoNNeR"},
    {id:"oneplus-13",brand:"OnePlus",model:"OnePlus 13",price:74990,os:"Android",screen:6.82,hz:120,chip:"Snapdragon 8 Elite",ram:12,storage:256,camera:50,zoom:3,battery:6000,charge:100,weight:210,score:95,features:["esim","wireless","telephoto","fast"],water:"IP69",source:"PhoNNeR"},
    {id:"xiaomi-15",brand:"Xiaomi",model:"Xiaomi 15",price:69990,os:"Android",screen:6.36,hz:120,chip:"Snapdragon 8 Elite",ram:12,storage:256,camera:50,zoom:2.6,battery:5240,charge:90,weight:191,score:93,features:["esim","wireless","telephoto","fast"],water:"IP68",source:"PhoNNeR"},
    {id:"nothing-3",brand:"Nothing",model:"Phone (3)",price:69990,os:"Android",screen:6.67,hz:120,chip:"Snapdragon 8s Gen 4",ram:12,storage:256,camera:50,zoom:3,battery:5150,charge:65,weight:218,score:87,features:["esim","wireless","telephoto","fast"],water:"IP68",source:"PhoNNeR"},
    {id:"zenfone-12",brand:"ASUS",model:"Zenfone 12 Ultra",price:89990,os:"Android",screen:6.78,hz:144,chip:"Snapdragon 8 Elite",ram:16,storage:512,camera:50,zoom:3,battery:5500,charge:65,weight:220,score:90,features:["esim","wireless","telephoto","fast"],water:"IP68",source:"PhoNNeR"}
  ].map((p,i)=>({...p,accent:accents[i%accents.length],screenType:"—",resolution:"—",front:0,video:"—",dimensions:"—",material:"—",network5g:true,nfc:true,launchDate:"",sim:"—"}));

  const I18N = {
    ru:{catalog:"Каталог",compare:"Сравнение",eyebrow:"✦ умный подбор смартфона",hero1:"Сравнивай глубже.",hero2:"Выбирай точнее.",heroCopy:"Ищи не только по названию — пиши требования обычными словами.",placeholder:"Например: компактный Android с eSIM…",cameraQuery:"камерофон 120 Гц",compactQuery:"компактный с eSIM",batteryQuery:"автономный Android",connecting:"Подключение к базе характеристик…",connected:n=>`Подключено ${n} моделей из внешней базы`,fallback:"Внешняя база недоступна — работает резервный каталог",filters:"☷ Фильтры",reset:"Сбросить",brand:"Бренд",priceTo:"Цена до",features:"Возможности",best:"Сначала лучшие",cheap:"Сначала дешевле",expensive:"Сначала дороже",batterySort:"Больше батарея",face:"Лицом к лицу",deep:"Глубокое сравнение",compareCopy:"Лучшее значение в каждой строке подсвечено.",footer:"Характеристики: Phone Specs API, GSMArena и PhoNNeR. Цены могут отличаться по региону.",phones:n=>`${n} смартфонов`,from:"от",unknown:"нет данных",added:"✓ Добавлен",add:"⇄ Сравнить",empty:"Ничего не нашлось",emptyCopy:"Убери один из фильтров или сократи запрос.",more:"Показать ещё",oneMore:"+ ещё один",choose:n=>`Выбери ещё ${n} смартфон для сравнения.`,score:"Сводная оценка",price:"Цена",screen:"Экран",screenType:"Тип экрана",resolution:"Разрешение",chip:"Процессор",memory:"Память",camera:"Основная камера",front:"Фронтальная камера",video:"Видео",battery:"Батарея",charge:"Зарядка",wireless:"Беспроводная зарядка",weight:"Вес",water:"Защита",network:"Сеть",nfc:"NFC",dimensions:"Размеры",material:"Материал",launch:"Дата выхода",yes:"Да",no:"Нет",auto:"Авто",themeSystem:"Тема: системная",themeLight:"Тема: светлая",themeDark:"Тема: тёмная",esim:"eSIM",telephoto:"Телеобъектив",fast:"Быстрая зарядка"},
    en:{catalog:"Catalog",compare:"Compare",eyebrow:"✦ smart phone finder",hero1:"Compare deeper.",hero2:"Choose smarter.",heroCopy:"Search beyond model names — describe what you need in plain language.",placeholder:"Example: compact Android with eSIM…",cameraQuery:"camera phone 120 Hz",compactQuery:"compact with eSIM",batteryQuery:"long battery Android",connecting:"Connecting to the specifications database…",connected:n=>`${n} external database models connected`,fallback:"External database unavailable — using the fallback catalog",filters:"☷ Filters",reset:"Reset",brand:"Brand",priceTo:"Price up to",features:"Features",best:"Best first",cheap:"Lowest price",expensive:"Highest price",batterySort:"Largest battery",face:"Head to head",deep:"Deep comparison",compareCopy:"The better value in each row is highlighted.",footer:"Specifications: Phone Specs API, GSMArena and PhoNNeR. Prices vary by region.",phones:n=>`${n} phones`,from:"from",unknown:"no data",added:"✓ Added",add:"⇄ Compare",empty:"No matches",emptyCopy:"Remove a filter or shorten your query.",more:"Show more",oneMore:"+ one more",choose:n=>`Choose ${n} more phone to compare.`,score:"Overall score",price:"Price",screen:"Display",screenType:"Display type",resolution:"Resolution",chip:"Chipset",memory:"Memory",camera:"Main camera",front:"Front camera",video:"Video",battery:"Battery",charge:"Charging",wireless:"Wireless charging",weight:"Weight",water:"Protection",network:"Network",nfc:"NFC",dimensions:"Dimensions",material:"Material",launch:"Launch date",yes:"Yes",no:"No",auto:"Auto",themeSystem:"Theme: system",themeLight:"Theme: light",themeDark:"Theme: dark",esim:"eSIM",telephoto:"Telephoto",fast:"Fast charging"},
    uk:{catalog:"Каталог",compare:"Порівняння",eyebrow:"✦ розумний підбір смартфона",hero1:"Порівнюй глибше.",hero2:"Обирай точніше.",heroCopy:"Шукай не лише за назвою — опиши вимоги звичайними словами.",placeholder:"Наприклад: компактний Android з eSIM…",cameraQuery:"камерофон 120 Гц",compactQuery:"компактний з eSIM",batteryQuery:"автономний Android",connecting:"Підключення до бази характеристик…",connected:n=>`Підключено ${n} моделей із зовнішньої бази`,fallback:"Зовнішня база недоступна — працює резервний каталог",filters:"☷ Фільтри",reset:"Скинути",brand:"Бренд",priceTo:"Ціна до",features:"Можливості",best:"Спочатку найкращі",cheap:"Спочатку дешевші",expensive:"Спочатку дорожчі",batterySort:"Більша батарея",face:"Віч-на-віч",deep:"Глибоке порівняння",compareCopy:"Найкраще значення в кожному рядку підсвічено.",footer:"Характеристики: Phone Specs API, GSMArena і PhoNNeR. Ціни можуть відрізнятися.",phones:n=>`${n} смартфонів`,from:"від",unknown:"немає даних",added:"✓ Додано",add:"⇄ Порівняти",empty:"Нічого не знайдено",emptyCopy:"Прибери фільтр або скороти запит.",more:"Показати ще",oneMore:"+ ще один",choose:n=>`Обери ще ${n} смартфон для порівняння.`,score:"Загальна оцінка",price:"Ціна",screen:"Екран",screenType:"Тип екрана",resolution:"Роздільність",chip:"Процесор",memory:"Пам’ять",camera:"Основна камера",front:"Фронтальна камера",video:"Відео",battery:"Батарея",charge:"Заряджання",wireless:"Бездротове заряджання",weight:"Вага",water:"Захист",network:"Мережа",nfc:"NFC",dimensions:"Розміри",material:"Матеріал",launch:"Дата виходу",yes:"Так",no:"Ні",auto:"Авто",themeSystem:"Тема: системна",themeLight:"Тема: світла",themeDark:"Тема: темна",esim:"eSIM",telephoto:"Телеоб’єктив",fast:"Швидке заряджання"},
    es:{catalog:"Catálogo",compare:"Comparar",eyebrow:"✦ buscador inteligente",hero1:"Compara mejor.",hero2:"Elige con precisión.",heroCopy:"Busca más allá del nombre: describe lo que necesitas.",placeholder:"Ejemplo: Android compacto con eSIM…",cameraQuery:"móvil cámara 120 Hz",compactQuery:"compacto con eSIM",batteryQuery:"Android gran batería",connecting:"Conectando con la base de especificaciones…",connected:n=>`${n} modelos conectados`,fallback:"Base externa no disponible — usando el catálogo de reserva",filters:"☷ Filtros",reset:"Restablecer",brand:"Marca",priceTo:"Precio hasta",features:"Funciones",best:"Mejores primero",cheap:"Más baratos",expensive:"Más caros",batterySort:"Mayor batería",face:"Cara a cara",deep:"Comparación profunda",compareCopy:"El mejor valor de cada fila está resaltado.",footer:"Especificaciones: Phone Specs API, GSMArena y PhoNNeR. Los precios varían por región.",phones:n=>`${n} teléfonos`,from:"desde",unknown:"sin datos",added:"✓ Añadido",add:"⇄ Comparar",empty:"Sin resultados",emptyCopy:"Quita un filtro o acorta la búsqueda.",more:"Mostrar más",oneMore:"+ uno más",choose:n=>`Elige ${n} teléfono más para comparar.`,score:"Puntuación",price:"Precio",screen:"Pantalla",screenType:"Tipo de pantalla",resolution:"Resolución",chip:"Procesador",memory:"Memoria",camera:"Cámara principal",front:"Cámara frontal",video:"Vídeo",battery:"Batería",charge:"Carga",wireless:"Carga inalámbrica",weight:"Peso",water:"Protección",network:"Red",nfc:"NFC",dimensions:"Dimensiones",material:"Material",launch:"Lanzamiento",yes:"Sí",no:"No",auto:"Auto",themeSystem:"Tema: sistema",themeLight:"Tema: claro",themeDark:"Tema: oscuro",esim:"eSIM",telephoto:"Teleobjetivo",fast:"Carga rápida"}
  };

  const $ = selector => document.querySelector(selector);
  const num = value => Number(String(value ?? "").replace(",", ".").match(/\d+(?:\.\d+)?/)?.[0] || 0);
  const keyOf = p => `${p.brand} ${p.model}`.toLowerCase().replace(/[^a-z0-9а-яё]+/g, "");
  const brandAccent = brand => accents[[...brand].reduce((a,c)=>a+c.charCodeAt(0),0)%accents.length];
  let phones = [...fallback], selected = ["s25-ultra", "oneplus-13"], brandSet = new Set(), featureSet = new Set();
  let visibleLimit = 48, lastSignature = "", databaseCount = 0;
  let languageChoice = localStorage.getItem("phonner-language") || "auto";
  let lang = languageChoice === "auto" ? resolveLanguage() : languageChoice;
  let themeMode = localStorage.getItem("phonner-theme") || "system";

  const search = $("#search"), price = $("#price"), sort = $("#sort");
  function resolveLanguage(){const code=(navigator.language||"en").toLowerCase();return code.startsWith("ru")?"ru":code.startsWith("uk")?"uk":code.startsWith("es")?"es":"en"}
  function t(key,...args){const value=(I18N[lang]||I18N.en)[key]??I18N.en[key]??key;return typeof value==="function"?value(...args):value}
  function money(n){return new Intl.NumberFormat(lang==="uk"?"uk-UA":lang==="ru"?"ru-RU":lang==="es"?"es-ES":"en-US").format(n)}
  function normalize(raw,index){
    const screen=num(raw.screen_size), hz=num(raw.refresh_rate), ram=num(raw.ram), storage=num(raw.storage), camera=num(raw.rear_camera_main), battery=num(raw.battery_capacity), charge=num(raw.charging_wired), weight=num(raw.weight);
    const cameraText=String(raw.rear_camera_specs||"").toLowerCase(), sim=String(raw.sim_type||"");
    const features=[];if(/esim/i.test(sim))features.push("esim");if(raw.charging_wireless&&String(raw.charging_wireless).trim())features.push("wireless");if(/长焦|tele|periscope|潜望/i.test(cameraText))features.push("telephoto");if(raw.fast_charging||charge>=45)features.push("fast");
    const score=Math.max(55,Math.min(98,Math.round(56+Math.min(hz,144)/12+Math.min(ram,16)/2+Math.min(battery,6000)/1000+Math.min(camera,200)/25+(raw.water_resistance?3:0)+(raw.network_5g?2:0)+(raw.nfc?2:0))));
    return {id:`db-${raw.id||index}`,brand:raw.brand||"Unknown",model:raw.model_name||raw.model||"Unknown",price:0,os:/ios/i.test(raw.os||"")?"iOS":raw.os||"Android",screen,hz,chip:raw.chipset||"—",ram,storage,camera,zoom:0,battery,charge,weight,score,features,water:raw.water_resistance||"—",screenType:raw.screen_type||"—",resolution:raw.resolution||"—",front:num(raw.front_camera),video:raw.video||"—",wireless:raw.charging_wireless||"—",dimensions:raw.dimensions||"—",material:raw.material||"—",network5g:Boolean(raw.network_5g),nfc:Boolean(raw.nfc),launchDate:raw.launch_date||"—",sim:sim||"—",accent:brandAccent(raw.brand||String(index)),source:"Phone Specs API"};
  }
  function mergeDatabase(external){const map=new Map(fallback.map(p=>[keyOf(p),p]));external.map(normalize).forEach(p=>{const key=keyOf(p),local=map.get(key);map.set(key,local?{...p,...local,source:"PhoNNeR + DB"}:p)});phones=[...map.values()].sort((a,b)=>(b.launchDate||"").localeCompare(a.launchDate||""));databaseCount=external.length}
  async function loadDatabase(){try{const response=await fetch(DATABASE_URL,{cache:"no-cache"});if(!response.ok)throw new Error(response.status);const data=await response.json();if(!Array.isArray(data)||data.length<100)throw new Error("invalid database");mergeDatabase(data);$("#db-dot").classList.add("ready");$("#db-status").textContent=t("connected",databaseCount);buildFilters();render()}catch(error){$("#db-status").textContent=t("fallback");console.warn("PhoNNeR database fallback",error)}}

  function match(p,query){const q=query.toLowerCase().replaceAll("ё","е").trim();if(!q)return true;const hay=[p.brand,p.model,p.os,p.chip,p.screenType,p.resolution,p.water,p.sim,...p.features,p.hz+" hz гц",p.ram+" gb гб",p.storage+" gb гб",p.camera+" mp мп",p.battery+" mah мач"].join(" ").toLowerCase();return q.split(/\s+/).every(token=>{if(["флагман","топ","flagship","premium"].includes(token))return p.score>=90;if(["компактный","маленький","compact","compacto"].includes(token))return p.screen>0&&p.screen<=6.4;if(["автономный","батарея","battery","batería","батарея"].includes(token))return p.battery>=5000;if(["камера","камерофон","camera","cámara"].includes(token))return p.camera>=48;if(["андроид","android"].includes(token))return /android/i.test(p.os);if(["айфон","iphone","ios"].includes(token))return p.os==="iOS";const amount=Number(token.replace(/\D/g,""));if(amount>=20000)return p.price>0&&p.price<=amount;return hay.includes(token)})}
  function filteredPhones(){let list=phones.filter(p=>match(p,search.value)&&(p.price===0||p.price<=+price.value)&&(!brandSet.size||brandSet.has(p.brand))&&[...featureSet].every(f=>p.features.includes(f)));list.sort((a,b)=>sort.value==="asc"?(a.price||Infinity)-(b.price||Infinity):sort.value==="desc"?(b.price||-1)-(a.price||-1):sort.value==="battery"?b.battery-a.battery:b.score-a.score);return list}
  function resultLabel(n){return t("phones",n)}
  function phoneSummary(p){const bits=[p.chip,p.screenType,p.battery?`${p.battery} mAh`:""].filter(x=>x&&x!=="—");return bits.join(" · ")||t("unknown")}
  function render(){
    const signature=[search.value,price.value,sort.value,[...brandSet].join(),[...featureSet].join(),lang].join("|");if(signature!==lastSignature){visibleLimit=48;lastSignature=signature}
    const list=filteredPhones(), shown=list.slice(0,visibleLimit);$("#result-title").textContent=resultLabel(list.length);$("#price-label").textContent=money(+price.value)+" ₽";$("#clear").style.display=search.value?"block":"none";
    $("#grid").innerHTML=shown.length?shown.map((p,i)=>`<article class="card" style="--phone:${p.accent};animation-delay:${Math.min(i,5)*35}ms"><div class="card-top"><span class="orb"><i>${escapeHtml(p.brand[0]||"?")}</i></span><span class="score"><b>${p.score}</b><small>/100</small></span></div><div class="title"><small>${escapeHtml(p.brand)} · ${escapeHtml(p.os)}</small><h3>${escapeHtml(p.model)}</h3><p>${escapeHtml(phoneSummary(p))}</p></div><div class="specs"><span>◫ ${p.screen||"—"}″ · ${p.hz||"—"} Hz</span><span>◈ ${p.ram||"—"}/${p.storage||"—"} GB</span><span>◎ ${p.camera||"—"} MP</span><span>ϟ ${p.battery||"—"} mAh</span></div><div class="bottom"><div class="price"><small>${p.price?t("from"):t("price")}</small><b>${p.price?money(p.price)+" ₽":t("unknown")}</b></div><span class="source-tag">${escapeHtml(p.source)}</span><button class="add ${selected.includes(p.id)?"on":""}" data-id="${escapeHtml(p.id)}">${selected.includes(p.id)?t("added"):t("add")}</button></div></article>`).join(""):`<div class="empty"><b>${t("empty")}</b><p>${t("emptyCopy")}</p></div>`;
    const more=$("#load-more");more.style.display=list.length>visibleLimit?"block":"none";more.textContent=`${t("more")} · ${list.length-visibleLimit}`;document.querySelectorAll(".add").forEach(button=>button.onclick=()=>toggle(button.dataset.id));dock();
  }
  function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]))}
  function toggle(id){selected=selected.includes(id)?selected.filter(item=>item!==id):selected.length<2?[...selected,id]:[selected[1],id];render()}
  function dock(){const pair=selected.map(id=>phones.find(p=>p.id===id)).filter(Boolean);$("#nav-count").textContent=selected.length;$("#dock-items").innerHTML=pair.map(p=>`<span>${escapeHtml(p.model)} <button data-x="${escapeHtml(p.id)}">×</button></span>`).join("")+(selected.length<2?`<span>${t("oneMore")}</span>`:"");document.querySelectorAll("[data-x]").forEach(button=>button.onclick=()=>toggle(button.dataset.x));$("#dock-action").className=selected.length===2?"":"off";$("#dock-action").textContent=t("compare")+" →";compare(pair)}
  function value(p,key){return p[key]===0||p[key]===false?p[key]:p[key]||"—"}
  function compare(pair){
    const out=$("#comparison");if(pair.length<2){out.innerHTML=`<div class="nothing">${t("choose",2-pair.length)}</div>`;return}
    const rows=[
      ["score","score","max",v=>`${v} / 100`],["price","price","min",v=>v?`${money(v)} ₽`:t("unknown")],["screen","screen","none",(v,i)=>`${v||"—"}″ · ${pair[i].hz||"—"} Hz`],["screenType","screenType","none",v=>v],["resolution","resolution","none",v=>v],["chip","chip","none",v=>v],["memory","ram","max",(v,i)=>`${v||"—"} / ${pair[i].storage||"—"} GB`],["camera","camera","max",v=>v?`${v} MP`:"—"],["front","front","max",v=>v?`${v} MP`:"—"],["video","video","none",v=>v],["battery","battery","max",v=>v?`${money(v)} mAh`:"—"],["charge","charge","max",v=>v?`${v} W`:"—"],["wireless","wireless","none",v=>v],["weight","weight","min",v=>v?`${v} g`:"—"],["water","water","none",v=>v],["network","network5g","boolean",v=>v?"5G":"4G"],["nfc","nfc","boolean",v=>v?t("yes"):t("no")],["dimensions","dimensions","none",v=>v],["material","material","none",v=>v],["launch","launchDate","none",v=>v]
    ];
    out.innerHTML=`<div class="table"><div class="row"><div></div><div>${escapeHtml(pair[0].model)}</div><div>${escapeHtml(pair[1].model)}</div></div>${rows.map(row=>{const vals=pair.map(p=>value(p,row[1]));const numeric=vals.every(v=>typeof v==="number"&&v>0);const best=numeric&&row[2]==="max"?Math.max(...vals):numeric&&row[2]==="min"?Math.min(...vals):null;return `<div class="row"><div>${t(row[0])}</div>${vals.map((v,i)=>`<div class="${best!==null&&v===best&&vals[0]!==vals[1]?"winner":""}">${best!==null&&v===best&&vals[0]!==vals[1]?"✓ ":""}${escapeHtml(row[3](v,i))}</div>`).join("")}</div>`}).join("")}</div>`;
  }
  function buildFilters(){const brands=[...new Set(phones.map(p=>p.brand))].sort();$("#brands").innerHTML=brands.map(brand=>`<label><input type="checkbox" value="${escapeHtml(brand)}" ${brandSet.has(brand)?"checked":""}><span>${escapeHtml(brand)}</span><small>${phones.filter(p=>p.brand===brand).length}</small></label>`).join("");document.querySelectorAll("#brands input").forEach(input=>input.onchange=()=>{input.checked?brandSet.add(input.value):brandSet.delete(input.value);render()});const featureKeys=["esim","wireless","telephoto","fast"];$("#features").innerHTML=featureKeys.map(key=>`<button class="pill ${featureSet.has(key)?"on":""}" data-f="${key}">${t(key)}</button>`).join("");document.querySelectorAll("[data-f]").forEach(button=>button.onclick=()=>{featureSet.has(button.dataset.f)?featureSet.delete(button.dataset.f):featureSet.add(button.dataset.f);button.classList.toggle("on");render()})}
  function applyLanguage(){document.documentElement.lang=lang;$("#nav-catalog").textContent=t("catalog");$("#nav-compare").textContent=t("compare");$("#eyebrow").textContent=t("eyebrow");$("#hero-title").innerHTML=`${t("hero1")}<br><span>${t("hero2")}</span>`;$("#hero-copy").textContent=t("heroCopy");search.placeholder=t("placeholder");const suggestions=document.querySelectorAll(".suggestions button");suggestions[0].textContent=t("cameraQuery");suggestions[1].textContent=t("compactQuery");suggestions[2].textContent=t("batteryQuery");$("#catalog-kicker").textContent=t("catalog");$("#filters-title").textContent=t("filters");$("#reset").textContent=t("reset");$("#brand-title").textContent=t("brand");$("#price-title").textContent=t("priceTo");$("#features-title").textContent=t("features");sort.options[0].text=t("best");sort.options[1].text=t("cheap");sort.options[2].text=t("expensive");sort.options[3].text=t("batterySort");$("#compare-kicker").textContent=t("face");$("#compare-title").textContent=t("deep");$("#compare-copy").textContent=t("compareCopy");$("#dock-title").textContent=`⇄ ${t("compare")}`;$("#footer-copy").textContent=t("footer");$("#load-more").textContent=t("more");$("#db-status").textContent=databaseCount?t("connected",databaseCount):t("connecting");buildFilters();render();updateThemeButton()}
  function effectiveDark(){return themeMode==="dark"||(themeMode==="system"&&matchMedia("(prefers-color-scheme: dark)").matches)}
  function applyTheme(){document.body.classList.toggle("dark",effectiveDark());document.documentElement.style.colorScheme=effectiveDark()?"dark":"light";updateThemeButton()}
  function updateThemeButton(){const button=$("#theme");button.textContent=themeMode==="system"?"◐":themeMode==="light"?"☀":"☾";button.title=t(themeMode==="system"?"themeSystem":themeMode==="light"?"themeLight":"themeDark")}

  [search,price,sort].forEach(input=>input.addEventListener("input",render));$("#clear").onclick=()=>{search.value="";render()};document.querySelectorAll(".suggestions button").forEach(button=>button.onclick=()=>{search.value=button.textContent;render();$("#catalog").scrollIntoView()});$("#reset").onclick=()=>{search.value="";price.value=130000;brandSet.clear();featureSet.clear();buildFilters();render()};$("#load-more").onclick=()=>{visibleLimit+=48;lastSignature=[search.value,price.value,sort.value,[...brandSet].join(),[...featureSet].join(),lang].join("|");render()};
  $("#language").value=languageChoice;$("#language").onchange=event=>{languageChoice=event.target.value;localStorage.setItem("phonner-language",languageChoice);lang=languageChoice==="auto"?resolveLanguage():languageChoice;applyLanguage()};
  $("#theme").onclick=()=>{themeMode=themeMode==="system"?"light":themeMode==="light"?"dark":"system";localStorage.setItem("phonner-theme",themeMode);applyTheme()};matchMedia("(prefers-color-scheme: dark)").addEventListener("change",()=>{if(themeMode==="system")applyTheme()});
  document.addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key==="k"){event.preventDefault();search.focus()}});
  applyTheme();applyLanguage();loadDatabase();
})();
